'use strict';
const data=JSON.parse(document.getElementById('dataset').textContent);
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n).toLocaleString('tr-TR');
const pct=n=>'%'+(n*100).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2});
const icons={grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',chart:'<path d="M4 3v17h17M8 15v-4m5 4V7m5 8V4"/>',database:'<ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v14c0 4 16 4 16 0V5M4 12c0 4 16 4 16 0"/>',flask:'<path d="M9 3h6m-5 0v7l-6 9c-1 2 1 2 2 2h12c2 0 3 0 2-2l-6-9V3M7 15h10"/>',book:'<path d="M12 5c-3-3-6-2-9-1v15c3-1 6-1 9 1 3-2 6-2 9-1V4c-3-1-6-2-9 1v15"/>',shield:'<path d="M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6zM8 12l3 3 5-6"/>',download:'<path d="M12 3v12m-4-4 4 4 4-4M4 16v5h16v-5"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 0 1 6 0c0 2-3 2-3 4m0 3h.01"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10h.01"/>',check:'<path d="m5 12 4 4 10-10"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',bolt:'<path d="m13 2-9 12h7l-1 8 10-13h-7z"/>'};
function icon(name){return `<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.info}</svg>`;}
function decorate(){document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));}
const pageNames={overview:'Genel bakış',models:'Model karşılaştırma',dataset:'Veri seti',experiment:'Jev deneyi',method:'Yöntem & kaynaklar'};
function route(){let view=location.hash.slice(1)||'overview';if(!(view in pageNames))view='overview';document.querySelectorAll('.page').forEach(el=>el.hidden=el.id!==`page-${view}`);document.querySelectorAll('[data-view]').forEach(el=>{el.classList.toggle('active',el.dataset.view===view);if(el.dataset.view===view)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});$('breadcrumb').textContent=pageNames[view];document.title=`${pageNames[view]} — Jev Review Lab`;document.querySelector('.sidebar').classList.remove('open');$('menu-toggle').setAttribute('aria-expanded','false');window.scrollTo(0,0);}
window.addEventListener('hashchange',route);
$('menu-toggle').onclick=()=>{const open=document.querySelector('.sidebar').classList.toggle('open');$('menu-toggle').setAttribute('aria-expanded',String(open));};
document.addEventListener('click',e=>{if(!e.target.closest('.sidebar,#menu-toggle')){document.querySelector('.sidebar').classList.remove('open');$('menu-toggle').setAttribute('aria-expanded','false');}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('.sidebar').classList.remove('open');$('menu-toggle').setAttribute('aria-expanded','false');}});
let toastTimer;
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3000);}
function download(name,content,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('Dosya hazır. İndirme başlatıldı.');}
document.querySelectorAll('[data-export]').forEach(el=>el.onclick=()=>download(el.dataset.export==='manifest'?'dataset-manifest.json':'model-results.json',JSON.stringify(el.dataset.export==='manifest'?data.manifest:{local:data.local,external_matched:data.comparisons},null,2)));
const best=[...data.local].sort((a,b)=>b.test.accuracy-a.test.accuracy)[0];
const fastest=[...data.local].sort((a,b)=>a.single_p50_ms-b.single_p50_ms)[0];
const statItems=[['database','Çalışma veri seti',fmt(data.manifest.selected_rows),'Dengeli dağılım','6.000 + 6.000'],['target','En yüksek doğruluk',pct(best.test.accuracy),best.model,'Test kümesinde'],['chart','Karşılaştırılan modeller',String(data.local.length),'Yerel model','Jev sonuç bekliyor'],['bolt','En düşük p50 gecikme',fastest.single_p50_ms.toFixed(2).replace('.',',')+' ms',fastest.model,'24 tekil tahmin']];
$('stats').innerHTML=statItems.map(([i,label,value,detail,note])=>`<article class="stat"><div class="stat-top">${esc(label)}<span class="stat-icon">${icon(i)}</span></div><div class="stat-value">${esc(value)}</div><div class="stat-bottom"><b>${esc(detail)}</b><span>· ${esc(note)}</span></div></article>`).join('');
$('performance-chart').innerHTML=[...data.local].sort((a,b)=>b.test.accuracy-a.test.accuracy).map(r=>`<div class="chart-row"><span class="chart-label">${esc(r.model)}</span><div class="chart-track"><div class="chart-bar" style="width:${100*r.test.accuracy}%"></div></div><strong class="chart-value">${pct(r.test.accuracy)}</strong></div>`).join('')+'<div class="chart-axis"><span>0</span><span>25</span><span>50</span><span>75</span><span>100</span></div>';
const labelName=label=>label==='positive'?'Olumlu':'Olumsuz';
const badge=label=>`<span class="sentiment ${label==='negative'?'negative':''}">${label==='positive'?'↗':'↘'} ${labelName(label)}</span>`;
const splitNames={train:'Eğitim',validation:'Doğrulama',test:'Test'};
const allReviews=data.explorer||[];
const reviewMap=new Map(allReviews.map(row=>[row.id,row]));
const pilotIds=new Set(data.reviews.map(row=>row.id));
const pilotReviews=[...pilotIds].map(id=>reviewMap.get(id)).filter(Boolean);
const agreement=row=>{const preds=Object.values(row.predictions||{});return {n:preds.length,correct:preds.filter(p=>p===row.label).length};};
$('sample-reviews').innerHTML=pilotReviews.slice(0,3).map(row=>{const agree=agreement(row);return `<article class="sample"><div class="sample-top">${badge(row.label)}<span class="sample-id">#${esc(row.id.slice(0,7))}</span></div><p>${esc(row.text)}</p><div class="sample-bottom"><span>${agree.correct}/${agree.n} model kaynak etiketle uyumlu</span><button data-review="${esc(row.id)}" aria-label="Yorum detayını aç">İncele ↗</button></div></article>`;}).join('');
let metricSplit='test',sortDesc=true;
function renderModels(){const sorted=[...data.local].sort((a,b)=>(b[metricSplit].accuracy-a[metricSplit].accuracy)*(sortDesc?1:-1));$('model-table').innerHTML=sorted.map((r,index)=>`<tr><td><div class="model-cell"><span class="model-monogram">${esc(r.model.split(' ').map(s=>s[0]).join(''))}</span>${esc(r.model)}</div></td><td><strong>${pct(r[metricSplit].accuracy)}</strong></td><td>${r[metricSplit].macro_f1.toFixed(4)}</td><td>${r.single_p50_ms.toFixed(2)} ms</td><td>${r.fit_seconds.toFixed(3)} sn</td><td><span class="sentiment">Yerel · $0</span></td></tr>`).join('');$('split-note').textContent=metricSplit==='test'?'Sabit test kümesi · 1.200 olumlu / 1.200 olumsuz':'Ön deney · 12 olumlu / 12 olumsuz';renderMatrix();}
$('sort-accuracy').onclick=()=>{sortDesc=!sortDesc;$('sort-accuracy').textContent='DOĞRULUK '+(sortDesc?'↓':'↑');renderModels();};
document.querySelectorAll('[data-split]').forEach(el=>el.onclick=()=>{metricSplit=el.dataset.split;document.querySelectorAll('[data-split]').forEach(button=>{button.classList.toggle('active',button===el);button.setAttribute('aria-pressed',String(button===el));});renderModels();});
$('matrix-model').innerHTML=data.local.map((r,i)=>`<option value="${i}">${esc(r.model)}</option>`).join('');
function renderMatrix(){const m=data.local[Number($('matrix-model').value)][metricSplit].confusion_matrix;$('matrix').innerHTML=`<span></span><span class="matrix-label">Olumsuz</span><span class="matrix-label">Olumlu</span><span class="matrix-label">Olumsuz</span><div class="matrix-box correct">${fmt(m[0][0])}</div><div class="matrix-box">${fmt(m[0][1])}</div><span class="matrix-label">Olumlu</span><div class="matrix-box">${fmt(m[1][0])}</div><div class="matrix-box correct">${fmt(m[1][1])}</div>`;}
$('matrix-model').onchange=renderMatrix;
$('external-results').innerHTML=data.comparisons.length?'<div class="table-scroll"><table><thead><tr><th>MODEL / EŞLEŞTİRME</th><th>n</th><th>DOĞRULUK</th><th>F1</th></tr></thead><tbody>'+data.comparisons.map(r=>`<tr><td>${esc(r.model)}</td><td>${r.n}</td><td>${pct(r.accuracy)}</td><td>${r.macro_f1.toFixed(4)}</td></tr>`).join('')+'</tbody></table></div>':`<div class="empty-state"><span class="empty-symbol">${icon('flask')}</span><h3>Ölçülmeyi bekleyen bir karşılaştırma.</h3><p>Jev ve diğer dil modelleri henüz çalıştırılmadı. Sonuçlar geldiğinde aynı örnekler üzerinde burada görünecek.</p><a class="button secondary" href="#experiment">Pilot planını incele ↗</a></div>`;
let pageIndex=0,filtered=[];const pageSize=12;
function filterReviews(){const query=$('review-search').value.toLocaleLowerCase('tr').trim(),split=$('review-split').value,label=$('review-label').value,errors=$('review-errors').checked;filtered=allReviews.filter(row=>(split==='all'||(split==='pilot'?pilotIds.has(row.id):row.split===split))&&(label==='all'||row.label===label)&&(!query||row.text.toLocaleLowerCase('tr').includes(query)||row.id.includes(query))&&(!errors||Object.values(row.predictions||{}).some(p=>p!==row.label)));pageIndex=0;renderReviews();}
function renderReviews(){const start=pageIndex*pageSize,slice=filtered.slice(start,start+pageSize);$('review-table').innerHTML=slice.length?slice.map(row=>{const a=agreement(row);return `<tr><td><div class="review-text">${esc(row.text)}</div><div class="review-sub">#${esc(row.id)}</div></td><td>${badge(row.label)}</td><td>${splitNames[row.split]}</td><td><span class="agreement ${a.correct<a.n?'partial':''}">${a.n?`${a.correct}/${a.n} doğru`:'Tahmin yok'}</span></td><td><button class="icon-button" data-review="${esc(row.id)}" aria-label="Yorum detayını aç">↗</button></td></tr>`;}).join(''):'<tr><td colspan="5"><div class="empty-state"><h3>Bu filtrelerle yorum bulunamadı.</h3><p>Aramayı veya filtreleri değiştirmeyi dene. Eğitim ve doğrulama kümesi için tahmin üretilmedi.</p></div></td></tr>';$('review-count').textContent=filtered.length?`${fmt(start+1)}–${fmt(Math.min(start+pageSize,filtered.length))} / ${fmt(filtered.length)} yorum`:'0 yorum';$('page-count').textContent=`${filtered.length?pageIndex+1:0} / ${Math.ceil(filtered.length/pageSize)}`;$('prev-page').disabled=pageIndex===0;$('next-page').disabled=start+pageSize>=filtered.length;}
['review-search','review-split','review-label','review-errors'].forEach(id=>$(id).addEventListener(id==='review-search'?'input':'change',filterReviews));
$('prev-page').onclick=()=>{pageIndex--;renderReviews();};$('next-page').onclick=()=>{pageIndex++;renderReviews();};
function csvCell(value){let s=String(value??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
$('export-reviews').onclick=()=>{const columns=['id','text','label','split'];const text='\ufeff'+[columns.join(','),...filtered.map(row=>columns.map(k=>csvCell(row[k])).join(','))].join('\r\n');download('review-lab-filtered.csv',text,'text/csv;charset=utf-8');};
document.addEventListener('click',event=>{const button=event.target.closest('[data-review]');if(!button)return;const row=reviewMap.get(button.dataset.review);if(!row)return;$('review-detail').innerHTML=`${badge(row.label)} <span class="muted">${splitNames[row.split]} · #${esc(row.id)}</span><p>${esc(row.text)}</p><div class="detail-predictions">${Object.entries(row.predictions||{}).map(([model,prediction])=>`<div><span>${esc(model)}</span><span>${badge(prediction)} ${prediction===row.label?'✓':'✕'}</span></div>`).join('')||'<span class="muted">Bu bölümde model tahmini yok. Yalnızca test kümesi değerlendirildi.</span>'}</div>`;$('review-dialog').showModal();});
$('close-dialog').onclick=()=>$('review-dialog').close();$('review-dialog').addEventListener('click',e=>{if(e.target===$('review-dialog')){const r=$('review-dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('review-dialog').close();}});
$('batch-cards').innerHTML=data.packets.map((packet,i)=>`<section class="panel batch-card"><div class="batch-number">PAKET 0${i+1}</div><div class="batch-title"><h2>${i===0?'İlk ölçümü al.':'Sonucu genişlet.'}</h2><span class="sentiment">${data.jev_completed_batches.includes(i+1)?'Sonuç kaydedildi':'İstek hazır'}</span></div><p>${i===0?'İlk yanıtın etiketlerini ve ücret başlıklarını incele.':'İlk denemenin sonucunu kontrol ettikten sonra çalıştır.'}</p><div class="batch-stats"><div><strong>${packet.state.length}</strong><span>yorum</span></div><div><strong>${Object.keys(packet.questions).length}</strong><span>bağımsız soru</span></div><div><strong>1</strong><span>hedef kredi</span></div></div><button class="button secondary" data-packet="${i}">${icon('download')} İstek JSON’unu indir</button></section>`).join('');
document.querySelectorAll('[data-packet]').forEach(el=>el.onclick=()=>download(`jev-request-${Number(el.dataset.packet)+1}.json`,JSON.stringify(data.packets[Number(el.dataset.packet)],null,2)));
document.querySelectorAll('[data-prompt]').forEach(el=>el.onclick=()=>download(`llm-prompt-${el.dataset.prompt}.txt`,data.prompts[Number(el.dataset.prompt)-1],'text/plain;charset=utf-8'));
const m=data.manifest;const journey=[[fmt(m.raw_rows),'Gerçek yorum · kaynak veri'],[fmt(m.conflicting_rows_removed),'Çelişkili etiketli satır çıkarıldı'],[fmt(m.duplicate_rows_removed),'Normalleştirilmiş tekrar çıkarıldı'],[fmt(m.selected_rows),'Dengeli çalışma seti'],['8.400 / 1.200 / 2.400','Eğitim / doğrulama / test']];
$('data-journey').innerHTML=journey.map(([value,label],i)=>`<div class="journey-step"><span>0${i+1}</span><div><strong>${value}</strong><small>${label}</small></div></div>`).join('');
$('source-revision').innerHTML=`Sabit veri sürümü: <code>${esc(m.revision)}</code><br>Ham dosya SHA-256: <code>${esc(m.raw_sha256)}</code>`;
decorate();renderModels();filterReviews();route();
